swagger: "2.0"
info:
  description: |
    This is a RESTFul API for Passenger data store.
  version: 1.0.0
  title: CustomerData
  contact:
    name: Travel Costa
    url: http://www.travel.com
    email: architecture@travel.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:8243
basePath: /customer/1.0.0
schemes:
 - https
 - http
consumes:
 - application/json
produces:
 - application/json
security:
 -
  default: []
paths:
  /getcustomers:
    get:
      description: Return all the customers
      parameters: []
      responses:
        "200":
          description: OK. List of APIs is returned.
          headers: {}
        "304":
          description: Not Modified. Empty body because the client has already the latest version of the requested resource.
        "406":
          description: Not Acceptable. The requested media type is not supported
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /bookings/{customerId}:
    get:
      description: Get bookings by ID
      parameters:
       -
        name: customerId
        in: path
        description: customer Id
        required: true
        type: string
        format: string
      responses:
        "200":
          description: OK Requested routs will be returned
          headers: {}
        "304":
          description: Not Modified. Empty body because the client has already the latest version of the requested resource.
        "404":
          description: Not Found. Requested API does not exist.
        "406":
          description: Not Acceptable. The requested media type is not supported
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /customer/{cityId}:
    get:
      description: Get details of customers by city ID
      parameters:
       -
        name: cityId
        in: path
        description: City Id
        required: true
        type: string
        format: string
      responses:
        "200":
          description: OK Requested routs will be returned
          headers: {}
        "304":
          description: Not Modified. Empty body because the client has already the latest version of the requested resource.
        "404":
          description: Not Found. Requested API does not exist.
        "406":
          description: Not Acceptable. The requested media type is not supported
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
securityDefinitions:
  default:
    type: oauth2
    authorizationUrl: https://test.com
    flow: implicit
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - testKey
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - https://run.mocky.io/v3/3c8f2964-0389-4ea9-b71a-3ba6290ca09d
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - https://run.mocky.io/v3/3c8f2964-0389-4ea9-b71a-3ba6290ca09d
  type: http
x-wso2-basePath: /customer/1.0.0/1.0.0
x-wso2-transports:
 - http
 - https
x-wso2-application-security:
  security-types:
   - oauth2
  optional: false
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
